/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.FitnessCenter.ui;

import com.ACE_FitnessCenter.helper.DateHelper;
import com.ACE_FitnessCenter.helper.DialogHelper;
import com.ACE_FitnessCenter.helper.utilityHelper;
import com.FitnessCenter.dao.TheoDoiDao;
import com.FitnessCenter.entity.CaTap;
import com.FitnessCenter.entity.DichVu;
import com.FitnessCenter.entity.HoiVien;
import com.FitnessCenter.entity.TheoDoi;
import static java.awt.Color.white;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mycomputer
 */
public class TheoDoiJDialog extends javax.swing.JFrame {

    TheoDoiDao dao = new TheoDoiDao();
    int index;
    DefaultTableModel model;
    String b;

    /**
     * Creates new form TheoDoiJDialog
     */
    public TheoDoiJDialog(String a) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.load(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTheoDoi = new javax.swing.JTable();
        txtSodovong1 = new javax.swing.JTextField();
        txtCanNang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSodovong2 = new javax.swing.JTextField();
        txtSodovong3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnCapNhatHoiVien = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        btnCapNhatHoiVien1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtIDtuan = new javax.swing.JTextField();
        txtNgayTheoDoi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbltrolai = new javax.swing.JLabel();
        lblMaHv = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACE_FitnessCenter - Quản lý theo dõi hội viên");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Theo Dõi Hội Viên");

        jLabel1.setText("Mã Hội Viên");

        tblTheoDoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Theo Dõi", "Mã Hội Viên", "Cân Nặng", "Số Đo vòng 1", "Số Đo vòng 2", "Số Đo vòng 3", "Ngày Theo Dõi", "Ghi Chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTheoDoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTheoDoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTheoDoi);

        jLabel2.setText("Cân nặng");

        jLabel4.setText("Ngày Theo Dõi");

        jLabel5.setText("Số Đo Vòng 1");

        jLabel6.setText("Số Đo Vòng 2");

        jLabel7.setText("Số Đo Vòng 3");

        jLabel8.setText("Ghi Chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        btnCapNhatHoiVien.setText("Sửa Theo Dõi");
        btnCapNhatHoiVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatHoiVienActionPerformed(evt);
            }
        });

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        btnCapNhatHoiVien1.setText("Cập Nhật Theo Dõi");
        btnCapNhatHoiVien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatHoiVien1ActionPerformed(evt);
            }
        });

        jLabel9.setText("ID Tuần");

        jButton1.setText("Mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbltrolai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltrolai.setForeground(new java.awt.Color(255, 0, 0));
        lbltrolai.setText("Trở lại");
        lbltrolai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbltrolaiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel1)
                            .addGap(27, 27, 27))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel9)
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtIDtuan, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addComponent(txtNgayTheoDoi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblMaHv, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSodovong1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSodovong3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSodovong2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCanNang, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(489, 489, 489))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltrolai, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1001, 1001, 1001)
                .addComponent(btnDong)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addComponent(btnCapNhatHoiVien1)
                .addGap(66, 66, 66)
                .addComponent(btnCapNhatHoiVien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCapNhatHoiVien, btnCapNhatHoiVien1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8)
                                    .addComponent(txtCanNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(lblMaHv, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(3, 3, 3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(txtIDtuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNgayTheoDoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSodovong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtSodovong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSodovong3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCapNhatHoiVien1)
                            .addComponent(btnCapNhatHoiVien))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDong))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbltrolai, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCapNhatHoiVien, btnCapNhatHoiVien1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTheoDoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTheoDoiMouseClicked
        try {
            //this.index = tblTheoDoi.rowAtPoint(evt.getPoint());
            // edit();
            if (tblTheoDoi.getRowCount() >= 0) {
                index = tblTheoDoi.getSelectedRow();
                ShowDetail();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblTheoDoiMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

//        setVisible(true);

    }//GEN-LAST:event_formWindowOpened

    private void btnCapNhatHoiVien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatHoiVien1ActionPerformed
        try {
            if (utilityHelper.checkNullText(txtCanNang)
                    && utilityHelper.checkNullText(txtSodovong2)
                    && utilityHelper.checkNullAreaText(txtGhiChu)
                    && utilityHelper.checkNullText(txtSodovong3)
                    && utilityHelper.checkNullText(txtSodovong1)) {

                {
                    if (utilityHelper.checkCanNang(txtCanNang)
                            && utilityHelper.checkVong1(txtSodovong1)
                            && utilityHelper.checkVong2(txtSodovong2)
                            && utilityHelper.checkVong3(txtSodovong3)) {

                        insert(lblMaHv.getText());
                        clear();

                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCapNhatHoiVien1ActionPerformed

    private void btnCapNhatHoiVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatHoiVienActionPerformed
        try {
            if (utilityHelper.checkNullText(txtCanNang)
                    && utilityHelper.checkNullText(txtSodovong2)
                    && utilityHelper.checkNullAreaText(txtGhiChu)
                    && utilityHelper.checkNullText(txtSodovong3)
                    && utilityHelper.checkNullText(txtSodovong1)) {

                {
                    if (utilityHelper.checkCanNang(txtCanNang)
                            && utilityHelper.checkVong1(txtSodovong1)
                            && utilityHelper.checkVong2(txtSodovong2)
                            && utilityHelper.checkVong3(txtSodovong3)) {

                        update(txtIDtuan.getText());
                        clear();

                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnCapNhatHoiVienActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnDongActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbltrolaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltrolaiMouseClicked
      this.dispose();
      new HoiVienJDialog().setVisible(true);
    }//GEN-LAST:event_lbltrolaiMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TheoDoiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TheoDoiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TheoDoiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TheoDoiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TheoDoiJDialog().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatHoiVien;
    private javax.swing.JButton btnCapNhatHoiVien1;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMaHv;
    private javax.swing.JLabel lbltrolai;
    private javax.swing.JTable tblTheoDoi;
    private javax.swing.JTextField txtCanNang;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtIDtuan;
    private javax.swing.JTextField txtNgayTheoDoi;
    private javax.swing.JTextField txtSodovong1;
    private javax.swing.JTextField txtSodovong2;
    private javax.swing.JTextField txtSodovong3;
    // End of variables declaration//GEN-END:variables

    private void update(String a) {
        TheoDoi model = getModel();
        try {
            dao.Update(model);
            this.loadSua(a);
            DialogHelper.alert(this, "Sửa thành công!");
        } catch (Exception e) {
            DialogHelper.alert(this, "Sửa thất bại!");
            e.printStackTrace();
        }
    }

    private void clear() {
        setTrang();

       // this.setStatus(true);
    }

    public void setTrang() {
        txtCanNang.setBackground(white);
        txtSodovong1.setText("");
        txtSodovong2.setText("");
        txtSodovong3.setText("");
        txtGhiChu.setText("");
        txtNgayTheoDoi.setText("");
    }

  

    TheoDoi getModel() {
        TheoDoi model = new TheoDoi();
        model.setIDtheodoi(txtIDtuan.getText());
        model.setCanNang(Float.valueOf(txtCanNang.getText()));
        model.setSoDov1(Float.valueOf(txtSodovong1.getText()));
        model.setSoDov2(Float.valueOf(txtSodovong2.getText()));
        model.setSodov3(Float.valueOf(txtSodovong3.getText()));
        model.setGhiChu(txtGhiChu.getText());
        model.setMahv(lblMaHv.getText());

        return model;
    }

    private void delete(String a) {
        if (DialogHelper.confirm(this, "Bạn thực sự muốn xóa cột theo dõi tuần này?")) {
            String id = txtIDtuan.getText();
            try {
                dao.delete(id);
                this.load(a);
                this.clear();
                DialogHelper.alert(this, "Xóa thành công!");
            } catch (HeadlessException e) {
                e.printStackTrace();
                DialogHelper.alert(this, "Xóa thất bại!");
            }
        }
    }

    private void ShowDetail() {
        model = (DefaultTableModel) tblTheoDoi.getModel();
        txtIDtuan.setText(model.getValueAt(index, 0).toString());
        lblMaHv.setText(model.getValueAt(index, 1).toString());
        txtCanNang.setText(model.getValueAt(index, 2).toString());
        txtSodovong1.setText(model.getValueAt(index, 3).toString());
        txtSodovong2.setText(model.getValueAt(index, 4).toString());
        txtSodovong3.setText(model.getValueAt(index, 5).toString());
        txtNgayTheoDoi.setText(model.getValueAt(index, 6).toString());
        txtGhiChu.setText(model.getValueAt(index, 7).toString());
        tblTheoDoi.setRowSelectionInterval(index, index);
    }

    private void load(String Mahv) {
        DefaultTableModel model = (DefaultTableModel) tblTheoDoi.getModel();
        model.setRowCount(0);
        try {

            List<TheoDoi> list = dao.selecttheoID(Mahv);

            for (TheoDoi nh : list) {
                Object[] row = {
                    nh.getIDtheodoi(),
                    nh.getMahv(),
                    nh.getCanNang(),
                    nh.getSoDov1(),
                    nh.getSoDov2(),
                    nh.getSodov3(),
                    nh.getNgayTheoDoi(),
                    nh.getGhiChu(),};

                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    private void loadSua(String IDtheodoi) {
        DefaultTableModel model = (DefaultTableModel) tblTheoDoi.getModel();
        model.setRowCount(0);
        try {

            List<TheoDoi> list = dao.selecttheoIDtheodoi(IDtheodoi);

            for (TheoDoi nh : list) {
                Object[] row = {
                    nh.getIDtheodoi(),
                    nh.getMahv(),
                    nh.getCanNang(),
                    nh.getSoDov1(),
                    nh.getSoDov2(),
                    nh.getSodov3(),
                    nh.getNgayTheoDoi(),
                    nh.getGhiChu(),};

                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    private void edit() {
        setTrang();
        try {
            String maHv = (String) tblTheoDoi.getValueAt(this.index, 0);
            TheoDoi model = dao.findById(maHv);
            if (model != null) {
                this.setModel(model);

            }
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    private void setModel(TheoDoi model) {
        txtIDtuan.setText(model.getIDtheodoi());
        lblMaHv.setText(model.getMahv());
        txtCanNang.setText(String.valueOf(model.getCanNang()));
        txtSodovong1.setText(String.valueOf(model.getSoDov1()));
        txtSodovong2.setText(String.valueOf(model.getSoDov2()));
        txtSodovong3.setText(String.valueOf(model.getSodov3()));
        txtNgayTheoDoi.setText(DateHelper.toString(model.getNgayTheoDoi()));
        txtGhiChu.setText(model.getGhiChu());

    }

    private void insert(String a) {
        TheoDoi model = getModel();
        try {
            dao.insert(model);
            this.load(a);
            this.clear();
            DialogHelper.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            DialogHelper.alert(this, "Thêm mới thất bại!");
        }
    }
}
